domain: mlflow
language: pytorch
project_slug: exploding_springfield
project_slug_no_hyphen: exploding_springfield
template_version: '2.0.0 # <<MLF-CORE_NO_BUMP>>'
template_handle: mlflow-pytorch
github_username: imipenem
creator_github_username: imipenem
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Phil
email: philipp_ehm@protonmail.com
project_name: exploding springfield
project_short_description: exploding springfield. A mlf-core based .
version: 0.1.0-SNAPSHOT
license: MIT
